version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: quback
      POSTGRES_PASSWORD: quback
      POSTGRES_DB: quback
    restart: always
    networks:
      - quback
networks:
  quback:
